package com.solomonprime.tricorder.ui

import androidx.compose.animation.core.*
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.Text
import androidx.compose.material3.TextField
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Button
import androidx.compose.foundation.text.KeyboardActions
import androidx.compose.foundation.text.KeyboardOptions
import androidx.compose.ui.text.input.ImeAction
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.foundation.clickable
import androidx.compose.ui.draw.clipToBounds
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.platform.LocalConfiguration
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.lifecycle.viewmodel.compose.viewModel
import com.solomonprime.tricorder.ui.theme.*
import com.solomonprime.tricorder.viewmodel.AiAnalysisViewModel
import com.solomonprime.tricorder.viewmodel.RadiationViewModel
import com.solomonprime.tricorder.viewmodel.AcousticViewModel
import com.solomonprime.tricorder.viewmodel.EnvironmentalViewModel
import com.solomonprime.tricorder.viewmodel.GeophysicalViewModel
import com.solomonprime.tricorder.viewmodel.BioScannerViewModel
import com.solomonprime.tricorder.viewmodel.PipeLeakViewModel

/**
 * AI Analysis Screen — LCARS-styled intelligent sensor analyst.
 *
 * Displays rolling AI insights generated by the rule-based analysis engine,
 * with a scrolling ticker summary and color-coded insight cards.
 */
@Composable
fun AiScreen(
    radViewModel: RadiationViewModel = viewModel(),
    acousticViewModel: AcousticViewModel? = null,
    envViewModel: EnvironmentalViewModel = viewModel(),
    geoViewModel: GeophysicalViewModel = viewModel(),
    bioViewModel: BioScannerViewModel = viewModel(),
    pipeViewModel: PipeLeakViewModel = viewModel(),
    aiViewModel: AiAnalysisViewModel = viewModel()
) {
    // Wire sensor lambdas to the AI engine
    LaunchedEffect(Unit) {
        aiViewModel.radCpm = { radViewModel.cpm.value }
        aiViewModel.acoDecibels = { acousticViewModel?.decibels?.value ?: 0f }
        aiViewModel.acoFreqBand = { acousticViewModel?.freqBand?.value ?: "unknown" }
        aiViewModel.envPressure = { envViewModel.pressure.value }
        aiViewModel.geoHeading = { geoViewModel.heading.value }
        aiViewModel.bioHeartRate = { bioViewModel.heartRate.value }
        aiViewModel.pipeLeakScore = { pipeViewModel.leakProbability.value }
        aiViewModel.startAnalysis()
    }

    DisposableEffect(Unit) {
        onDispose { aiViewModel.stopAnalysis() }
    }

    val insights by aiViewModel.insights.collectAsState()
    val summary by aiViewModel.currentSummary.collectAsState()

    Column(
        modifier = Modifier
            .fillMaxSize()
            .background(Color.Black)
            .padding(12.dp)
    ) {
        // --- LCARS Header ---
        LcarsHeader(title = "AI ANALYSIS")

        Spacer(modifier = Modifier.height(8.dp))

        // --- User Query Input ---
        var userQuery by remember { mutableStateOf("") }
        var isQuerying by remember { mutableStateOf(false) }
        
        Row(
            modifier = Modifier.fillMaxWidth(),
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalAlignment = Alignment.CenterVertically
        ) {
            OutlinedTextField(
                value = userQuery,
                onValueChange = { userQuery = it },
                modifier = Modifier.weight(1f),
                placeholder = { 
                    Text("Ask about sensor data...", color = LcarsTan.copy(0.5f)) 
                },
                colors = androidx.compose.material3.OutlinedTextFieldDefaults.colors(
                    focusedTextColor = LcarsTan,
                    unfocusedTextColor = LcarsTan,
                    focusedBorderColor = LcarsBlue,
                    unfocusedBorderColor = LcarsTan.copy(0.3f),
                    cursorColor = LcarsOrange
                ),
                singleLine = true,
                keyboardOptions = KeyboardOptions(imeAction = ImeAction.Send),
                keyboardActions = KeyboardActions(
                    onSend = {
                        if (userQuery.isNotBlank()) {
                            aiViewModel.processUserQuery(userQuery)
                            userQuery = ""
                        }
                    }
                )
            )
            Box(
                modifier = Modifier
                    .clip(RoundedCornerShape(8.dp))
                    .background(LcarsBlue)
                    .clickable {
                        if (userQuery.isNotBlank()) {
                            aiViewModel.processUserQuery(userQuery)
                            userQuery = ""
                        }
                    }
                    .padding(horizontal = 16.dp, vertical = 12.dp)
            ) {
                Text("ASK", color = LcarsBlack, fontWeight = FontWeight.Bold, fontSize = 14.sp)
            }
        }
        
        Spacer(modifier = Modifier.height(8.dp))
        
        // --- Scrolling Ticker Summary ---
        TickerSummary(text = summary)

        Spacer(modifier = Modifier.height(12.dp))

        // --- Insight Cards ---
        if (insights.isEmpty()) {
            // Empty state
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .weight(1f),
                contentAlignment = Alignment.Center
            ) {
                val infiniteTransition = rememberInfiniteTransition(label = "pulse")
                val alpha by infiniteTransition.animateFloat(
                    initialValue = 0.4f,
                    targetValue = 1f,
                    animationSpec = infiniteRepeatable(
                        animation = tween(1500, easing = EaseInOutSine),
                        repeatMode = RepeatMode.Reverse
                    ),
                    label = "pulseAlpha"
                )
                Text(
                    text = "MONITORING... All readings nominal.",
                    color = LcarsBlue.copy(alpha = alpha),
                    fontSize = 16.sp,
                    fontFamily = FontFamily.Monospace,
                    fontWeight = FontWeight.Bold
                )
            }
        } else {
            LazyColumn(
                modifier = Modifier.weight(1f),
                verticalArrangement = Arrangement.spacedBy(8.dp)
            ) {
                items(insights, key = { "${it.timestamp}-${it.sensorSource}" }) { insight ->
                    InsightCard(insight)
                }
            }
        }

        Spacer(modifier = Modifier.height(8.dp))

        // --- CLEAR Button ---
        if (insights.isNotEmpty()) {
            Box(
                modifier = Modifier
                    .fillMaxWidth()
                    .clip(RoundedCornerShape(4.dp))
                    .background(LcarsOrange)
                    .clickable { aiViewModel.clearInsights() }
                    .padding(vertical = 10.dp),
                contentAlignment = Alignment.Center
            ) {
                Text(
                    text = "CLEAR INSIGHTS",
                    color = Color.Black,
                    fontSize = 14.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = FontFamily.Monospace,
                    modifier = Modifier.padding(horizontal = 16.dp)
                )
            }
            Spacer(modifier = Modifier.height(4.dp))
        }

        // --- Footer ---
        Text(
            text = "ANALYSIS ENGINE v1.0 — Rule-based pattern matching. Not medical/safety advice.",
            color = LcarsTan.copy(alpha = 0.5f),
            fontSize = 10.sp,
            fontFamily = FontFamily.Monospace,
            modifier = Modifier.padding(top = 4.dp, bottom = 4.dp)
        )
    }
}

// --- LCARS Header Bar ---
@Composable
private fun LcarsHeader(title: String) {
    Row(
        modifier = Modifier.fillMaxWidth(),
        verticalAlignment = Alignment.CenterVertically
    ) {
        Box(
            modifier = Modifier
                .width(80.dp)
                .height(32.dp)
                .clip(RoundedCornerShape(topStart = 16.dp, bottomStart = 16.dp))
                .background(LcarsPurple)
        )
        Box(
            modifier = Modifier
                .weight(1f)
                .height(32.dp)
                .background(LcarsOrange),
            contentAlignment = Alignment.CenterEnd
        ) {
            Text(
                text = title,
                color = Color.Black,
                fontSize = 18.sp,
                fontWeight = FontWeight.Bold,
                fontFamily = FontFamily.Monospace,
                modifier = Modifier.padding(end = 12.dp)
            )
        }
        Box(
            modifier = Modifier
                .width(24.dp)
                .height(32.dp)
                .clip(RoundedCornerShape(topEnd = 16.dp, bottomEnd = 16.dp))
                .background(LcarsBlue)
        )
    }
}

// --- Scrolling Ticker ---
@Composable
private fun TickerSummary(text: String) {
    val screenWidth = LocalConfiguration.current.screenWidthDp.dp
    val infiniteTransition = rememberInfiniteTransition(label = "ticker")
    val offsetX by infiniteTransition.animateFloat(
        initialValue = screenWidth.value,
        targetValue = -screenWidth.value * 2,
        animationSpec = infiniteRepeatable(
            animation = tween(durationMillis = 12000, easing = LinearEasing),
            repeatMode = RepeatMode.Restart
        ),
        label = "tickerOffset"
    )

    Box(
        modifier = Modifier
            .fillMaxWidth()
            .height(28.dp)
            .clip(RoundedCornerShape(4.dp))
            .background(Color(0xFF1A1A2E))
            .clipToBounds()
    ) {
        Text(
            text = text,
            color = LcarsOrange,
            fontSize = 14.sp,
            fontWeight = FontWeight.Bold,
            fontFamily = FontFamily.Monospace,
            maxLines = 1,
            overflow = TextOverflow.Visible,
            modifier = Modifier
                .offset(x = offsetX.dp)
                .wrapContentWidth(unbounded = true)
        )
    }
}

// --- Insight Card ---
@Composable
private fun InsightCard(insight: AiAnalysisViewModel.AiInsight) {
    val borderColor = when (insight.severity) {
        "alert" -> LcarsRed
        "warning" -> LcarsOrange
        else -> LcarsBlue
    }

    val relativeTime = formatRelativeTime(insight.timestamp)

    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clip(RoundedCornerShape(4.dp))
            .background(Color(0xFF1A1A2E))
    ) {
        // Color-coded left border
        Box(
            modifier = Modifier
                .width(4.dp)
                .fillMaxHeight()
                .defaultMinSize(minHeight = 60.dp)
                .background(borderColor)
        )

        Column(
            modifier = Modifier
                .weight(1f)
                .padding(horizontal = 12.dp, vertical = 8.dp)
        ) {
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.SpaceBetween,
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = insight.title,
                    color = borderColor,
                    fontSize = 14.sp,
                    fontWeight = FontWeight.Bold,
                    fontFamily = FontFamily.Monospace
                )
                // Source sensor badge
                Box(
                    modifier = Modifier
                        .clip(RoundedCornerShape(4.dp))
                        .background(borderColor.copy(alpha = 0.2f))
                        .padding(horizontal = 6.dp, vertical = 2.dp)
                ) {
                    Text(
                        text = insight.sensorSource,
                        color = borderColor,
                        fontSize = 10.sp,
                        fontWeight = FontWeight.Bold,
                        fontFamily = FontFamily.Monospace
                    )
                }
            }

            Spacer(modifier = Modifier.height(4.dp))

            Text(
                text = insight.body,
                color = Color.White.copy(alpha = 0.85f),
                fontSize = 12.sp,
                fontFamily = FontFamily.Monospace,
                lineHeight = 16.sp
            )

            Spacer(modifier = Modifier.height(4.dp))

            Text(
                text = relativeTime,
                color = LcarsTan.copy(alpha = 0.5f),
                fontSize = 10.sp,
                fontFamily = FontFamily.Monospace
            )
        }
    }
}

// --- Relative time formatter ---
private fun formatRelativeTime(timestamp: Long): String {
    val now = System.currentTimeMillis()
    val diff = now - timestamp
    return when {
        diff < 60_000L -> "just now"
        diff < 3_600_000L -> "${diff / 60_000}m ago"
        diff < 86_400_000L -> "${diff / 3_600_000}h ago"
        else -> "${diff / 86_400_000}d ago"
    }
}
